name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Ajouter le répertoire Node.js au PATH
    - name: Add Node.js to PATH
      run: echo "/root/.nvm/versions/node/v20.11.1/bin" >> $GITHUB_PATH

    # Étape 2 : Vérification du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 3 : Supprimer l'ancien build
    - name: Remove old build
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          rm -rf .next

    # Étape 4 : Mise à jour du code sur le serveur
    - name: Update code on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          git pull origin master

    # Étape 5 : Installer les dépendances
    - name: Install dependencies
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          npm install

    # Étape 6 : Construire le projet
    - name: Build the project
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          npm run build

    # Étape 7 : Redémarrer PM2
    - name: Restart PM2 process
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          pm2 delete okaze
          pm2 start npm --name okaze -- run start