name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Configuration de Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # Étape 2 : Vérification du code source
    - name: Checkout code
      uses: actions/checkout@v4

    # Étape 3 : Supprimer l'ancien build
    - name: Remove old build
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          rm -rf .next

    # Étape 4 : Mise à jour du code sur le serveur
    - name: Update code on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          git pull origin master

    # Étape 5 : Installer les dépendances
    - name: Install dependencies
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 20.11.1
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          npm install

    # Étape 6 : Construire le projet
    - name: Build the project
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          nvm use 20.11.1
          echo "Checking Node.js version..."
          node -v
          echo "Checking npm version..."
          npm -v
          npm run build

    # Étape 7 : Redémarrer PM2
    - name: Restart PM2 process
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/okaze-reunion/htdocs/okaze-reunion-nextjs/
          pm2 delete okaze
          pm2 start npm --name okaze -- run start